import {
  Banner,
  Description,
  Section,
  Text,
  TextWrap,
  Title,
} from './About.styled';
import btnClose from '../../images/sprite.svg';
import imgDesktop from '../../images/about/about_desktop.png';
import imgTablet from '../../images/about/about_tablet.png';
import imgMobile from '../../images/about/about_mobile.png';

export const About = () => {
  return (
    <Section>
      <Title>
        a Story that started
        <br />
        with&nbsp;
        <span>
          one simple <br />
          ape
        </span>
      </Title>
      <Text>
        WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
        IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </Text>
      <TextWrap>
        <svg width="24" height="24">
          <use href={`${btnClose}#x`} />
        </svg>
        <Description>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </Description>
      </TextWrap>
      <img
        srcSet={`${imgMobile} 216w,  ${imgTablet} 313w, ${imgDesktop} 492w `}
        size="(max-width:480px) 216px, (max-width:480px) 313px, 492px"
        src={imgMobile}
        alt="monkey in cap"
      />
      <Banner>
        <div>
          <p>HAVE NO LIMITS</p>
          <svg width="36" height="36">
            <use href={`${btnClose}#x`} />
          </svg>
          <p>Break rules</p>
          <svg width="36" height="36">
            <use href={`${btnClose}#x`} />
          </svg>
          <p>Destroy stereotypes</p>
          <svg width="36" height="36">
            <use href={`${btnClose}#x`} />
          </svg>
        </div>
      </Banner>
    </Section>
  );
};
